sudo: required
services:
   - docker

before_install:
   - docker build -t melanieammonite/react-test -f ./client/Dockerfile.dev ./client

script:
   - docker run -e CI=true melanieammonite/react-test npm test

after_success:
   - docker build -t melanieammonite/multi-client ./client
   - docker build -t melanieammonite/multi-nginx ./nginx
   - docker built -t melanieammonite/multi-server ./server
   - docker built -t melanieammonite/multi-worker ./worker
   # Log in to docker CLI
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   # Take those images and push them to docker hub
   - docker push melanieammonite/multi-client
   - docker push melanieammonite/multi-nginx
   - docker push melanieammonite/multi-server
   - docker push melanieammonite/multi-worker
